language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
# no dependencies required
# install:
#  - pip install -r requirements.txt
# pytest - Test Suite for the Command Class
script:
  - pytest
